### ISSUE TITLE
validation checks error - possible improvement

### ISSUE THREAD

**Issue by daniejstriata** [fabio42/ssl-checker#7]
Can you improve the error messages? When a cert does not match the domain queried the word Error is the same color as the domain
![image](https://github.com/fabio42/ssl-checker/assets/13314239/5bd656d7-2144-4497-8219-da3f8075fe70)
Could the full error not be displayed when pressing enter with the list just giving highlights?

When running `ssl-checker` without any values there is no output or help printed.

**Comment by fabio42** [comment]
Thank you for your feedback @daniejstriata. I believe changed in #8 should address all of your suggestions.
